### ISSUE TITLE
Love the mod!

### ISSUE THREAD

**Issue by LastRaidBoss** [Provismet/ProviHealth#1]
Everything works great but would it be possible to add options to make the colors different like dark mode instead of light mode for example would be perfect. Also if color hues based on % of damage dealt like at 75% it turns slightly yellowish then 50% it's orange then 25% it starts turning bright red or something like that would be super dope not sure how easy that would be to add.

 thanks!

**Comment by Provismet** [comment]
1. I'm not sure what you mean by light and dark mode in this context. If you could send an illustration that would be great. Though if you mean to simply have darker textures you *can* already achieve this via a resource pack.

2. Colour-changing bars are theoretically possible. Though I would need to look into it and grayscale out the current bar textures.

**Comment by LastRaidBoss** [comment]
> 1. I'm not sure what you mean by light and dark mode in this context. If you could send an illustration that would be great. Though if you mean to simply have darker textures you _can_ already achieve this via a resource pack.
ok
> 2. Colour-changing bars are theoretically possible. Though I would need to look into it and grayscale out the current bar textures.
It would be cool for rpg servers where you kill packs of monsters seeing where you need to do dmg to lower hp ones just by looking at the colors yeah. but either way it's a great mod no issues or bugs super clean.

Question...
Is there anyway to show the health bars for mobs with invisibility tag for RPG servers who use invisible mob tags as a gimmick to add new mobs in vanilla? It sucks not seeing health of custom mobs due to them being normal minecraft mobs with invis potion tag also making the health invisible even though the actual new mob created by the server isn't.

**Comment by LastRaidBoss** [comment]
> > 1. I'm not sure what you mean by light and dark mode in this context. If you could send an illustration that would be great. Though if you mean to simply have darker textures you _can_ already achieve this via a resource pack.
> >    ok
> > 2. Colour-changing bars are theoretically possible. Though I would need to look into it and grayscale out the current bar textures.
> >    It would be cool for rpg servers where you kill packs of monsters seeing where you need to do dmg to lower hp ones just by looking at the colors yeah. but either way it's a great mod no issues or bugs super clean.
> 
> Question... Is there anyway to show the health bars for mobs with invisibility tag for RPG servers who use invisible mob tags as a gimmick to add new mobs in vanilla? It sucks not seeing health of custom mobs due to them being normal minecraft mobs with invis potion tag also making the health invisible even though the actual new mob created by the server isn't.

Plus damage indicators like something similiar to toro health has would be sweet I love the UI from this compared to toro tho but seeing dmg dealt is super nice for rpg servers/modpacks.

**Comment by Provismet** [comment]
> Question... Is there anyway to show the health bars for mobs with invisibility tag for RPG servers who use invisible mob tags as a gimmick to add new mobs in vanilla? It sucks not seeing health of custom mobs due to them being normal minecraft mobs with invis potion tag also making the health invisible even though the actual new mob created by the server isn't.

The decision to not render invisible mobs with health bars was intentional (the mod actually checks if the mob is invisible). It's to prevent the mod from being equivalent to cheating (seeing invisible players, illusioners, etc).  
I am able to disable this, but I don't have a viable method to distinguish a normal invisible mob from custom ones.

I also play RPG-like servers, so I have some ideas for partially resolving this. But if you could tell me more about the specifics, I can potentially add an exception (such as rendering health bars for invisible mobs that still have armour on).

> Plus damage indicators like something similiar to toro health has would be sweet I love the UI from this compared to toro tho but seeing dmg dealt is super nice for rpg servers/modpacks.

I am planning to add this feature eventually, I just need to find a good way to implement it. I am also soon adding armour points to the HUD.

**Comment by LastRaidBoss** [comment]
Here is an example for a mob that is like a ghostly set of armor
![javaw_tLoWYZXlXn](https://github.com/Provismet/ProviHealth/assets/153030562/68b08b80-2373-4a56-94bb-5c147986a5f5)

**Comment by LastRaidBoss** [comment]
> Here is an example for a mob that is like a ghostly set of armor ![javaw_tLoWYZXlXn](https://private-user-images.githubusercontent.com/153030562/288440027-68b08b80-2373-4a56-94bb-5c147986a5f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NzM0MzIsIm5iZiI6MTcwMTg3MzEzMiwicGF0aCI6Ii8xNTMwMzA1NjIvMjg4NDQwMDI3LTY4YjA4YjgwLTIzNzMtNGE1Ni05NGJiLTVjMTQ3OTg2YTVmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQxNDMyMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzcxY2Q4OGY1NGEyMmVjYWYyNTM0MDg5Mzk5NDdlYTg5YmNjODUyODViZDE2NzA2YmI1MDZiODBlMWRkZmM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6gguoF_kuupZldPz83qWNUPAqkmW4UOiKUy_pSPwG7s)

I'm not exactly sure what they did to create the custom mob all I know is it uses invisible tag so you don't see the base mob because that would make it look stupid. I know that for a fact because I've spoken directly to the devs and they confirmed it's because they have invisible tags which break some health mods. Toro Health does have a way to fix it inside the settings but it only works for hud not inworld bars for some reason.

**Comment by Provismet** [comment]
It looks to me like it's an invisible mob wearing armour and a Player Head.  
I've added a fix that will render the health bar for invisible mobs if one of the following conditions is met:
- Is wearing an item on its head.
- Is wearing an item on its chest.
- Has a rider (such as "DisplayEntities" which are sometimes used by plugins and datapacks).

Here's an example.
![image](https://github.com/Provismet/ProviHealth/assets/17149901/d6324296-7c4e-4d2c-a83c-1a05d8de5d2c)

This patch will be live in the next update alongside viewing armour points and hopefully damage particles.

**Comment by LastRaidBoss** [comment]
> It looks to me like it's an invisible mob wearing armour and a Player Head. I've added a fix that will render the health bar for invisible mobs if one of the following conditions is met:
> 
> * Is wearing an item on its head.
> * Is wearing an item on its chest.
> * Has a rider (such as "DisplayEntities" which are sometimes used by plugins and datapacks).
> 
> Here's an example. ![image](https://private-user-images.githubusercontent.com/17149901/288536626-d6324296-7c4e-4d2c-a83c-1a05d8de5d2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NDkxMDcsIm5iZiI6MTcwMTk0ODgwNywicGF0aCI6Ii8xNzE0OTkwMS8yODg1MzY2MjYtZDYzMjQyOTYtN2M0ZS00ZDJjLWE4M2MtMWEwNWQ4ZGU1ZDJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDExMzMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjY2U3NGM3NGE4YjNlMmU0MWUxODAxMjQ1M2EwNmE3OWRiZTdmZWExNDA1Y2NkOTEwY2IxOTNjN2Y0NDJmZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ObR2kE6j2POPCM5dJIyQNMmu35D9N0c_fXmnkgGj8hU)
> 
> This patch will be live in the next update alongside viewing armour points and hopefully damage particles.

Fucking awesome!

**Comment by LastRaidBoss** [comment]
> It looks to me like it's an invisible mob wearing armour and a Player Head. I've added a fix that will render the health bar for invisible mobs if one of the following conditions is met:
> 
> * Is wearing an item on its head.
> * Is wearing an item on its chest.
> * Has a rider (such as "DisplayEntities" which are sometimes used by plugins and datapacks).
> 
> Here's an example. ![image](https://private-user-images.githubusercontent.com/17149901/288536626-d6324296-7c4e-4d2c-a83c-1a05d8de5d2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNTQxMjMsIm5iZiI6MTcwMjI1MzgyMywicGF0aCI6Ii8xNzE0OTkwMS8yODg1MzY2MjYtZDYzMjQyOTYtN2M0ZS00ZDJjLWE4M2MtMWEwNWQ4ZGU1ZDJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDAwMTcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliMmUwOWQ1OTc4MzgwNzE3ZmQyOGM1MjVmZWExMGJmZjQ4OTY2NjZkODcyYmVmNzM2Njc4NjE0NDM1Y2FmYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k6bxeKVGyQoAQiemeCma788l2MGgvJyzJ43rbeGf5PI)
> 
> This patch will be live in the next update alongside viewing armour points and hopefully damage particles.

![javaw_d9Tt46dI0u](https://github.com/Provismet/ProviHealth/assets/153030562/05fd9a82-2fac-4a71-98e3-e5c37f4ce765)

Everything works great all the monsters have healthbars besides one mobtype which is slimes for some reason?

**Comment by LastRaidBoss** [comment]
> > It looks to me like it's an invisible mob wearing armour and a Player Head. I've added a fix that will render the health bar for invisible mobs if one of the following conditions is met:
> > 
> > * Is wearing an item on its head.
> > * Is wearing an item on its chest.
> > * Has a rider (such as "DisplayEntities" which are sometimes used by plugins and datapacks).
> > 
> > Here's an example. ![image](https://private-user-images.githubusercontent.com/17149901/288536626-d6324296-7c4e-4d2c-a83c-1a05d8de5d2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNTQxMjMsIm5iZiI6MTcwMjI1MzgyMywicGF0aCI6Ii8xNzE0OTkwMS8yODg1MzY2MjYtZDYzMjQyOTYtN2M0ZS00ZDJjLWE4M2MtMWEwNWQ4ZGU1ZDJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDAwMTcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliMmUwOWQ1OTc4MzgwNzE3ZmQyOGM1MjVmZWExMGJmZjQ4OTY2NjZkODcyYmVmNzM2Njc4NjE0NDM1Y2FmYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k6bxeKVGyQoAQiemeCma788l2MGgvJyzJ43rbeGf5PI)
> > This patch will be live in the next update alongside viewing armour points and hopefully damage particles.
> 
> ![javaw_d9Tt46dI0u](https://private-user-images.githubusercontent.com/153030562/289396600-05fd9a82-2fac-4a71-98e3-e5c37f4ce765.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNTQyMzAsIm5iZiI6MTcwMjI1MzkzMCwicGF0aCI6Ii8xNTMwMzA1NjIvMjg5Mzk2NjAwLTA1ZmQ5YTgyLTJmYWMtNGE3MS05OGUzLWU1YzM3ZjRjZTc2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQwMDE4NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYTk1ZTA5YzNjODdjYTY2YWQ2M2QwOTUwMDk0ZDQ2MmU5N2RkYjVkOGRhYjYyMjYxODY2NTAwYTNkZjgxYzI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FhWMcQGHusGu20aBvLKO5uMHNwcnsh-4tA5suZGG10I)
> 
> Everything works great all the monsters have healthbars besides one mobtype which is slimes for some reason?

oh and I mean the ingame healthbar the hud works but the actual health bar doesn't and yes I made sure I smacked it and damaged it too and it doesn't pop up still

**Comment by Provismet** [comment]
Is that Monumenta? The PORTAL strike? I can try and investigate why those slimes are different.

I have a couple guesses, and should be able to fix this soon if my guess is correct.

**Comment by Provismet** [comment]
In-world health bars don't render for mobs that have living passengers, so my guess is that this type of slime has an invisible armour stand riding it.  
(Armour Stands are classified as "living".)

I've already solved this armour stand problem in a developmental build.  
So if you can point me to where this slime spawns, I can test it ingame.

**Comment by LastRaidBoss** [comment]
> In-world health bars don't render for mobs that have living passengers, so my guess is that this type of slime has an invisible armour stand riding it. (Armour Stands are classified as "living".)
> 
> I've already solved this armour stand problem in a developmental build. So if you can point me to where this slime spawns, I can test it ingame.

wait do you know what server this is lol?

IP: server.playmonumenta.com

It's a common slime inside of P.O.R.T.A.L Strike in Region 3

**Comment by Provismet** [comment]
> wait do you know what server this is lol?

Yeah I love Monumenta, I'm also the person who made [the modpack with the custom main menu](https://modrinth.com/modpack/provis-monumenta-modpack) (will be updating it to 1.20.1 after I finish making some new art assets to integrate Monumenta's custom entity groups into the HUD portraits).

I'll head into PORTAL later today and see if the new changes work there.

**Comment by Provismet** [comment]
Looks like it was an armour stand issue after all.
![2023-12-11_22 54 34](https://github.com/Provismet/ProviHealth/assets/17149901/44e86de3-ffbf-4ea7-92e4-d5bb9ef74c4f)

This is now fixed as of mod version 1.2.0, which will be uploaded shortly.

**Comment by LastRaidBoss** [comment]
> Looks like it was an armour stand issue after all. ![2023-12-11_22 54 34](https://private-user-images.githubusercontent.com/17149901/289696438-44e86de3-ffbf-4ea7-92e4-d5bb9ef74c4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzOTAzOTIsIm5iZiI6MTcwMjM5MDA5MiwicGF0aCI6Ii8xNzE0OTkwMS8yODk2OTY0MzgtNDRlODZkZTMtZmZiZi00ZWE3LTkyZTQtZDViYjllZjc0YzRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDE0MDgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkZjY5MjMyMTVhYzE3MmI4NDg0ZDIzN2RhOTA4MTQxZjgxNDNkZTc4NDgyOTEzY2JjNDE2MTVlYTJmM2QwZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c3PWZDJ664d4KNrbZXX0z_qyfCOrD3Hw6SapFiXSzxw)
> 
> This is now fixed as of mod version 1.2.0, which will be uploaded shortly.

Awesome this is becoming one of the best health mods I've used. Sadly the new greyscale health bars don't work with most shaders can you add an option to switch the type of health bar rendering for ppl who only play with shaders on? Thanks

**Comment by Provismet** [comment]
It's definitely on my to-do list. Were the bars rendering properly before the colour changing feature was added?

**Comment by LastRaidBoss** [comment]
> It's definitely on my to-do list. Were the bars rendering properly before the colour changing feature was added?

yes I had to downgrade back to the 2nd release instead because I've used these shaders for so long I can't stand vanilla haha

**Comment by Provismet** [comment]
Thanks for the info, 1.2.1 is now on Modrinth. Note though that the compatibility mode for health bars will disable the colour changing feature (colour changing requires a Render Program that some shaders will break).

**Comment by LastRaidBoss** [comment]
> Thanks for the info, 1.2.1 is now on Modrinth. Note though that the compatibility mode for health bars will disable the colour changing feature (colour changing requires a Render Program that some shaders will break).

that's fine, that's like the only feature I could go without anyways looks great!
