### ISSUE TITLE
Health bars missing when using shaders

### ISSUE THREAD

**Issue by Billnotic** [Provismet/ProviHealth#21]
### Type of Error

Incorrect Behaviour

### Mod List

sodium 0.5.8
iris 1.7.0
fabric api 0.92.1
provihealth 1.2.4

### Description

Originally I discovered this in my massive forge modpack with sinytra connector, but I tested it with a smaller group of mods on fabric and it still occurred. Basically, turning on any shaders makes the health bar above mobs disappear, however the number containing their health remains.

### Mod Version

1.2.4

### Minecraft Version

1.20.1

### Mod Loader

Fabric

### Steps to Reproduce

Install the mod list, turn on a shader pack (I tested with BSL, Shrimple, Photon, and Bliss, all same result), then look at a mob. Normally it will have a health bar above it, now it does not.

**Comment by Provismet** [comment]
Did you try turning on compatibility mode in the settings?

**Comment by Billnotic** [comment]
Haha no, I'm dumb and can't read. My apologies.
