### ISSUE TITLE
[Suggestion] Make in-world health bars invisible with F1

### ISSUE THREAD

**Issue by Slooshie1** [Provismet/ProviHealth#27]
Title is self explanatory; I'd like the health bars to go away when hiding my HUD with F1. This could even be a setting that is toggled off by default. This would make taking screenshots of hurt mobs better without turning off health bars manually

**Comment by MrSquirrel250** [comment]
yo what button do i press to open settings menu for it??

**Comment by Slooshie1** [comment]
> yo what button do i press to open settings menu for it??

Install Mod Menu
