### ISSUE TITLE
Increase potential maximum health amount displayed above 1024

### ISSUE THREAD

**Issue by Vynderunel** [Provismet/ProviHealth#28]
### Type of Suggestion

Modify Existing Functionality

### Description

Maximum health displayed with ProviHealth seems to be capped at 1024. I would love to be able to see health values larger than 1024 accurately displayed with this mod.

### Reason

Listing this as a suggestion since I'm not sure if this is an issue with vanilla minecraft's health system or something that could be improved with the mod.

I'm using ProviHealth to have actual healthbars displayed above mobs for a RPG server that is heavily modified with plugins. As part of the server, the nameplate and their health % is shown for mobs but I'm using the mod to have a better visual representation and to see the exact health amounts.
 Many of the mobs and players have more than 1024 health but health beyond that amount isn't taken into account for the health bar. The bar works properly once the mobs are brought below 1024 heath but the bar still acts as if that were their actual maximum health.
![image](https://github.com/user-attachments/assets/cb3c9600-a51b-4d23-9c85-1fe3394bd321)
When injured but the hp amount is above 1024, it still displays as 1024 maxhp and full health.
![image](https://github.com/user-attachments/assets/13fb6c3d-d55b-4e8e-9edb-be0a934cabc9)
![image](https://github.com/user-attachments/assets/894cc375-838f-435c-9c0a-c67ad3abd9fa)

**Comment by Provismet** [comment]
This is a Minecraft limitation, the vanilla game client limits attributes to a maximum of 1024. The server's plugins are bypassing this upper-limit.

There is already a mod that fixes this, [AttributeFix](https://modrinth.com/mod/attributefix).

**Comment by Vynderunel** [comment]
Thanks for the explanation and your time!
