### ISSUE TITLE
Add an option to have your own player's health bar always visible

### ISSUE THREAD

**Issue by Spike-has-no-idea-how-to-code** [Provismet/ProviHealth#29]
### Type of Suggestion

New Feature

### Description

![2024-08-05_19 33 16](https://github.com/user-attachments/assets/496b7579-3d74-4795-93ac-fb6c84fd23fe)
Like this! (except this screenshot was taken in freecam which is why I can see my own healthbar)

**Comment by Spike-has-no-idea-how-to-code** [comment]
This seems like it shouldn't be too hard to code, seeing as the feature itself is already there, and it just needs some code to make it never go away. In the future, I would appreciate expanding upon this by adding details like your XP, and hunger and food info similar to appleskin. But for now, I want this to replace my current health bar.

**Comment by Provismet** [comment]
> **Reason**
> _No response_

I am genuinely curious as to why you want this.  
But I do believe other mods such as [Njol's HUD](https://modrinth.com/mod/njols-hud) are better implementations of what you're looking for.

**Comment by Spike-has-no-idea-how-to-code** [comment]
> > **Reason**
> > _No response_
> 
> I am genuinely curious as to why you want this. But I do believe other mods such as [Njol's HUD](https://modrinth.com/mod/njols-hud) are better implementations of what you're looking for.

I really enjoy the way your health bar is designed, but at the same time I don’t like it to be used for other mobs in the world (I prefer just the world health bars and the damage indicators) so it leaves a empty space where I would like to move my info to. I was looking for a mod to do such a thing that also had a good design, and yours was the best I’ve seen yet, so I was just requesting it become a real feature. I could settle for one of those mods, but again, I think your design looks cool. Of course, there is no pressure to do this since it is your choice, but I must give the suggestion either way.

**Comment by Provismet** [comment]
This is too far outside the scope of the mod and wouldn't really add much value to it. I recommend you simply go for a HUD mod like [Njol's](https://modrinth.com/mod/njols-hud) instead and make a texture pack for it if you want different visuals.
