### ISSUE TITLE
Health Bars rendering on top of blindness

### ISSUE THREAD

**Issue by LadyHaley** [Provismet/ProviHealth#30]
### Type of Error

Incorrect Behaviour

### Description

On my server, aggrod endermen give the player blindness to make them more difficult to stomp.
The health bars will render above their heads when they teleport away through the blindness, meaning you are able to see them coming when you shouldnt be able to.

### Mod Version

2.1.0+1.21

### Minecraft Version

1.21.0

### Mod Loader

Fabric

### Steps to Reproduce

Fight enderman with blindness, deal some damage, watch them teleport away while seeing their health bar through blindness

**Comment by Provismet** [comment]
Update: My current solution to this is to reduce the health bar render distance when the player has blindness, but this has to account for varying blindness levels (such as how darkness is larger), so it may take longer than I would have liked.
