### ISSUE TITLE
1.21 - Increasing ProviHealth Max render distance does nothing

### ISSUE THREAD

**Issue by Gamemassa** [Provismet/ProviHealth#32]
### Type of Error

Incorrect Behaviour

### Description

Maybe I'm misunderstanding what the "Maximum Render Distance" setting in the ProviHealth config file is supposed to do, but I increased it and I still have to be within a few blocks of the enemy I'm looking at for its health bar to pop up.

### Mod Version

2.1.0

### Minecraft Version

1.21

### Mod Loader

Fabric 0.16.3
Fabric API 0.102.0

### Steps to Reproduce

N/A

### Crash Log

```bash
N/A
```

**Comment by Provismet** [comment]
Max render distance controls the maximum distance (in blocks) that a mob can be from you in order for its health bar to render.

Examine the options menu again, the health bar will operate differently based on the type of mob in question.  
By default passive mobs (such as common animals) will not display a health bar unless they are at max health.  
Additionally, looking directly at a mob should display the health bar regardless at default settings.

This is why I need steps to reproduce the problem:
- What mob are you looking at? Have you tried hostile mobs? Passive mobs? other players?
- Are you looking directly at the mob in question?
- Is the mob at full health? Does this behaviour change after hitting the mob?
- What does the rest of your config file look like? Even screenshots from the cloth-config UI would suffice.

**Comment by Gamemassa** [comment]
> Max render distance controls the maximum distance (in blocks) that a mob can be from you in order for its health bar to render.
> 
> Examine the options menu again, the health bar will operate differently based on the type of mob in question. By default passive mobs (such as common animals) will not display a health bar unless they are at max health. Additionally, looking directly at a mob should display the health bar regardless at default settings.
> 
> This is why I need steps to reproduce the problem:
 
* What mob are you looking at? Have you tried hostile mobs? Passive mobs? other players?
I was looking at a wolf. I also tried a zombie and a Wandering Trader. I'm in SP so no other players to look at in this case.

* Are you looking directly at the mob in question?
Yes.

 * Is the mob at full health? Does this behaviour change after hitting the mob?
Yes, the all the mobs were at full health. No, this behavior didn't change after I attacked the zombie.

* What does the rest of your config file look like? Even screenshots from the cloth-config UI would suffice.
Here's my config file:
https://mclo.gs/y2P3myo

I'm actually having (what I assume is) an unrelated issue where my game crashes when I open the Cloth Config in-game in Mod Menu. I can send the Cloth config file if that works. I can also send my latest.log, if you think that will help.

**Comment by Gamemassa** [comment]
Also, thanks for the quick response!

**Comment by Provismet** [comment]
Thanks for the config file, I can now point out a partial cause of the issue:

> "bossHealth": "HIDE_IF_FULL",
> "bossTarget": true,
> "hostileHealth": "HIDE_IF_FULL",
> "hostileTarget": true,
> "playerHealth": "HIDE_IF_FULL",
> "playerTarget": true,
> "otherHealth": "HIDE_IF_FULL",
> "otherTarget": true,

With these settings, mobs that are at full health will not show health bars, but targeting (looking directly at the mob from up close) will show the health bar.  
The health bars *should* still show after damaging the mob though. Try changing "HIDE_IF_FULL" to "ALWAYS_SHOW".

**Comment by Provismet** [comment]
With a bit more investigation, even with similar "HIDE_IF_FULL" settings, health bars still render for me when the mob is damaged.

![image](https://github.com/user-attachments/assets/4c4baa10-7db6-4cf7-b14a-0bc8a4ed456b)

Do you have other any mods active?

**Comment by Gamemassa** [comment]
> Do you have other any mods active?

Uhhh...

_Looks at custom modpack of 400+ mods_

Yes, a lot of other mods. You should be able to see the whole list in my latest.log below.

https://mclo.gs/jL7vb1o

**Comment by Provismet** [comment]
It very likely to be that one of those 400 mods is interfering then. Testing it with only a small handful of mods with your same config shows no irregularities.

[testing.webm](https://github.com/user-attachments/assets/571c8c2f-8223-454b-ad48-14c03d908ce3)

**Comment by Gamemassa** [comment]
Oh, yipee. More binary testing. Pfft.

I'll keep you updated.

**Comment by Gamemassa** [comment]
> It very likely to be that one of those 400 mods is interfering then. Testing it with only a small handful of mods with your same config shows no irregularities.
> 
>  testing.webm

I just thought of something. Could it be Jade? I know that one also affects what happens when you look at things.

**Comment by Provismet** [comment]
Unlikely, when it comes to looking at things, PHB only reads your targeted mob (when you look at a mob and the sword crosshair appears, that's targeting).

Can you record your error, so I can get more information? Additionally, do you have a .mrpack of your modpack so I can verify my results with said recording?

**Comment by Gamemassa** [comment]
I'm not even sure if I know what a .mrpack is, so no, I don't think I have one.

When you say "record the error" what do you mean? Like a GIF or video?

**Comment by Provismet** [comment]
.mrpack is the filetype that Modrinth distributes modpacks with, if this is a custom modpack then you can export one via the Modrinth launcher (likely possible too with other launchers). If it's not a custom modpack, then just giving me the link to it would also suffice.

Yes, I mean a video or gif, preferably a video. I recommend a webm for better file size.

**Comment by Gamemassa** [comment]
I use the vanilla launcher and cobble my custom modpack together manually.

I can try to make a GIF or video.

**Comment by Gamemassa** [comment]
> .mrpack is the filetype that Modrinth distributes modpacks with, if this is a custom modpack then you can export one via the Modrinth launcher (likely possible too with other launchers). If it's not a custom modpack, then just giving me the link to it would also suffice.
> 
> Yes, I mean a video or gif, preferably a video. I recommend a webm for better file size.

Ok, I made a short video, as requested (and yes, I know there's a lot going on in my HUD; I still need to rearrange a few things).

[unknown_2024.09.02-17.26_1.webm](https://github.com/user-attachments/assets/4ba3bd96-857a-498a-ab28-8c146303ddaf)

**Comment by Provismet** [comment]
Thanks for the video.

That's intended behaviour for the default settings. Your settings, as per the config you posted earlier, set non-hostile mobs to `HIDE_IF_FULL`. The health bar is hidden because the mob is at full health.

Change your settings and try again. If you believe there's still an issue, then record another video, showing the mob getting damaged for example.

**Comment by Gamemassa** [comment]
> Thanks for the video.
> 
> That's intended behaviour for the default settings. Your settings, as per the config you posted earlier, set non-hostile mobs to `HIDE_IF_FULL`. The health bar is hidden because the mob is at full health.
> 
> Change your settings and try again. If you believe there's still an issue, then record another video, showing the mob getting damaged for example.

So after testing with it set to "SHOW" instead of "HIDE_IF_FULL", if I'm understanding this correctly, the "Max Render Distance" setting doesn't necessarily require me to be _looking at_ entities for their health bars to show up?

**Comment by Provismet** [comment]
Max Render Distance only applies specifically to mobs who's health bars would otherwise be visible. Look at my video again, the pig's health is visible even when not being looked at.

`SHOW`/`HIDE`/`HIDE IF FULL` will determine if a health bar is visible. Looking at a mob from up close (such that the HUD appears) will display the health bar regardless of the previous setting.  
If the previous two rules say that the health bar should render, then Max Render Distance is checked to see if the mob is too far.

**Comment by Gamemassa** [comment]
> Max Render Distance only applies specifically to mobs who's health bars would otherwise be visible. Look at my video again, the pig's health is visible even when not being looked at.
> 
> `SHOW`/`HIDE`/`HIDE IF FULL` will determine if a health bar is visible. Looking at a mob from up close (such that the HUD appears) will display the health bar regardless of the previous setting. If the previous two rules say that the health bar should render, then Max Render Distance is checked to see if the mob is too far.

Gotcha. Well, apologies for the miscommunication, since I originally misunderstood what that setting does. As far as the second thing you said, where looking at the enemy inside a certain distance overrides the SHOW/HIDE setting, is there any way to change the distance for that?

**Comment by Provismet** [comment]
No that's based on targeting, which should be equal to your attack range.

**Comment by Gamemassa** [comment]
> No that's based on targeting, which should be equal to your attack range.

Ohh, gotcha. Does the Spyglass have any effect on that?

**Comment by Provismet** [comment]
No it does not.
