### ISSUE TITLE
Mob Effects and armor visualization

### ISSUE THREAD

**Issue by JasdanVM** [Provismet/ProviHealth#33]
### Type of Suggestion

New Feature

### Description

Allow us to get a peak on what effects the mob is under, like, if they have regen.
### Reason

On the topic of competing standards, there's a health bar mod that adds those features.
But I like your portraits more, and the mount solution.
So, please consider adding similar characteristics.

**Comment by Provismet** [comment]
Good idea.

**Comment by Provismet** [comment]
Upon further inspection, status effects of mobs are not known client-side. Without a server-side mod, it's not possible to put this data on the healthbar.

Which health bar mod had visible potion effects?

**Comment by Provismet** [comment]
Issue resolved via colours. This feature is now implemented as of 2.2.0 for 1.21.3+.
