### ISSUE TITLE
New Strike Particles

### ISSUE THREAD

**Issue by JasdanVM** [Provismet/ProviHealth#34]
### Type of Suggestion

Modify Existing Functionality

### Description

Add Datadriven (if possible) particles that can be toggled in the config, for Critical Strikes, instakill attacks, when you affect the mod with Bleeding (like from the Majrusz's Progressive Difficulty mod), or fun things, like a "bullseye" target particle when you hit a mob in the head with a projectile.
If possible, multiple-kill indicators would be Awesome!
Like, if you kill 5 zombies with Sweeping Edge at the same time you'll see the "Pentakill" text pop up.

### Reason

This kind of feedback would make combat more dynamic and satisfying, plus, another reason to make this mod a more enticing Health Bar option.

**Comment by Provismet** [comment]
No. This is unnecessary for a health bar mod, it reaches more into the territory of a HUD overhaul.
