### ISSUE TITLE
Mod does not have compatibility with Mod Menu

### ISSUE THREAD

**Issue by defeder** [Provismet/ProviHealth#35]
### Type of Error

Incorrect Behaviour

### Mod List

- Mod Menu
- Provi's Health Bars

### Description

Mod Menu should be able to use the config for Provi's Health Bars but does not. From what I can see, Provi's Health Bars provides a way to use the config menu that is not disabled when Mod Menu is installed, leading to the config menu not being able to be accessed at all.

### Mod Version

1.20.4+1.20.2

### Minecraft Version

1.20.2

### Mod Loader

Fabric

### Steps to Reproduce

- Install mod menu
- Install provi's health bars
- Go into the mods tab of the menu
- Hover over the icon for Provi's Health Bars

**Comment by Provismet** [comment]
You need Mod Menu _AND_ Cloth Config to access the menu.
