### ISSUE TITLE
All Entity name tags are constantly visible

### ISSUE THREAD

**Issue by EvertBt** [Provismet/ProviHealth#36]
### Type of Error

Incorrect Behaviour

### Description

Traced the issue back to this mod but im confused it hasnt been noticed before. as title says, all entity nametags are always visible. For example invisible players and item frames with names items in them. Unable to find a setting to disable this.

### Mod Version

2.1.2+1.21.3

### Minecraft Version

1.21.3

### Mod Loader

Fabric

### Steps to Reproduce

Start a clean profile using the modrinth launcher, add fabric api (launcher 0.16.9), add this mod with mentioned version.
Rename an item and put it in a frame, then look at the frame and look away. The name will persist
![image](https://github.com/user-attachments/assets/07499845-e275-49e0-927b-a69f80e51d3c)

**Comment by Provismet** [comment]
I've confirmed the bug, I believe I caused this one when updating to 1.21.3 (they changed how rendering works) which is why it's new. The fix looks simple enough, so this should be resolved soon.
