### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by OneWorldStudio** [Provismet/ProviHealth#4]
Hello, can you make the mod work for you with the MythicMobs and ModelEngine plugin?

**Comment by OneWorldStudio** [comment]
https://modrinth.com/mod/provis-health-bars/gallery

**Comment by Provismet** [comment]
I am unable to add direct support for anything outside of the Fabric ecosystem, plugins are fully server-side and are not mods. The mobs they add are not "real" and are functionally illusions. It's not possible for the mod to detect them. However, if the plugin mobs are built on-top of an existing mob, then this might be possible.

Could you please give me an example of the issue? If you could describe the mobs that don't work (preferably with a screenshot or short video of the mod not working on them) then I can see if it's something I can solve.

Also please confirm which version of the mod you're using. A similar issue was solved in version 1.1.0 of the mod.

**Comment by OneWorldStudio** [comment]
voras:
  Type: IRON_GOLEM
  Display: 'Voras' 
  Health: 500
  Modules:
    ThreatTable: true
  AIGoalSelectors:
  - clear
  - meleeattack
  AITargetSelectors:
  - clear
  - players
  Options:
    PreventOtherDrops: true
    Despawn: true
    Persistent: false
    KnockbackResistance: 1
    Collidable: true
    Silent: true
    FollowRange: 32
    #MovementSpeed: 0.5
  Skills:
  - skill{s=voras_bossbar_damage} @self ~onDamaged
  - throw{v=1;vy=-1} @pir{r=2} ~onTimer:1  
  - skill{s=voras_venom} @target ~onTimer:45
  - skill{s=voras_web} @self ~onTimer:35
  - randomskill{s=voras_attack1_sync,voras_attack2_sync;sync=true} @self ~onAttack
  - skill{s=voras_death} @self ~onDeath
  - skill{s=voras_spawn} @self ~onSpawn
  - skill{s=voras_spawn_slowfalling} @self ~onTimer:20
  - skill{s=voras_spawn_land} @self ~onTimer:1
  - skill{s=voras_stun_50} @self ~onDamaged <50%
  - skill{s=voras_stun_25} @self ~onDamaged <25%
  - skill{s=voras_stun_hit} @self ~onDamaged
  - randomskill{skills=voras_50_bleed,voras_25_bleed} @self ~onTimer:2
  - model{mid=voras;d=false;i=true;lpitch=true;step=1} @self ~onSpawn
  - model{mid=voras;d=false;i=true;lpitch=true;step=1}} @self ~onLoad  
  - bodyclamp{m=voras;c=15} @self ~onSpawn  
  - bodyclamp{m=voras;c=15} @self ~onLoad  
  
![Screenshot_46](https://github.com/Provismet/ProviHealth/assets/136928305/40524f1d-21c7-4fc9-8a8a-6216c30f98ab)
![Screenshot_47](https://github.com/Provismet/ProviHealth/assets/136928305/731aece6-d0e1-4e95-b9f1-2d256174c0eb)
![Screenshot_45](https://github.com/Provismet/ProviHealth/assets/136928305/ad34d307-6359-4f34-aa2c-726fcfceed50)

  
  Mod Last Vervion
  
  
  
  I think it's possible to do this, even the Legendary ToolTip mod animates any item with a custom texture from ItemsAdder and any other texture from pack textures.

**Comment by Provismet** [comment]
So if I'm understanding this correctly this mob is an invisible Iron Golem with DisplayEntities moving around it?  
If so, then are the DisplayEntities being moved by the server plugin? Are any of them passengers of the Iron Golem?

**Comment by OneWorldStudio** [comment]
Yes, it's DisplayEntities, when I add a model, the vanilla mob hides behind the model.
Yes, there's a vanilla mob sitting in it, with a model already on it.

**Comment by OneWorldStudio** [comment]
All mobs on which there are DisplayEntities, move due to the plugin in which the engine is developed for this.

**Comment by Provismet** [comment]
I can make an experimental build that considers a mob "visible" if it is touching a DisplayEntity.

**Comment by OneWorldStudio** [comment]
I would be very grateful and would love to test this out. Could you also make it so that you can move the indicator. For example, to the center or to the upper right corner. Exactly which one is on the screen.

**Comment by OneWorldStudio** [comment]
![Screenshot_49](https://github.com/Provismet/ProviHealth/assets/136928305/0b681135-b391-4078-b886-f953e41a32f5)
![Screenshot_48](https://github.com/Provismet/ProviHealth/assets/136928305/a11ceffe-d72f-4b23-8c65-84c09e678672)

**Comment by Provismet** [comment]
> I would be very grateful and would love to test this out.

There is now a branch for this fix. Github won't let me send JAR files in comments, so instead you can find the auto-built JAR in the [build status](https://github.com/Provismet/ProviHealth/actions/runs/7148657685). It will download an Artifacts.zip containing the mod JAR and source.

> Could you also make it so that you can move the indicator. For example, to the center or to the upper right corner. Exactly which one is on the screen.

This is possible and I plan to add this feature, but it's not something I can implement quickly. The assets I drew are designed for the left-side and aren't symmetrical.  
To my knowledge Minecraft doesn't support simply flipping the textures, which means that all the health bar HUD textures would need to be manually duplicated and I would have to create a new registry system to accomodate this.

**Comment by OneWorldStudio** [comment]
1.1.1 did not display a custom mob

**Comment by Provismet** [comment]
Strange, I set the search radius to 5 blocks, which I assumed would be large enough for this purpose. I can confirm an invisible zombie standing next to a BlockDisplayEntity had visibile health bars.

I've pushed another [commit](https://github.com/Provismet/ProviHealth/actions/runs/7148870495). This one has a configurable search size in the config menu (incase the space between the Iron Golem and the DisplayEntities is larger than I thought).

Could you also enable hitboxes, set the Iron Golem to glow and take a screenshot of the custom mob please?

**Comment by OneWorldStudio** [comment]
![Screenshot_51](https://github.com/Provismet/ProviHealth/assets/136928305/464c6aa0-e2f9-4f3b-975f-49f59c72d785)
I do not know how to make it shine

**Comment by Provismet** [comment]
> I do not know how to make it shine

use `/effect give @e[type=minecraft:iron_golem] glowing` to grant glow to all Iron Golems for a short duration.

Do health bars (HUD or overhead) fail to show for all custom mobs? Or do some work? I have a suspicion that the health bar for the Voras monster might be rendering correctly but is hidden inside the custom mob due to its size.  
The health bars in the world can have their sizes scaled, does it become visible when at the maximum size?

**Comment by OneWorldStudio** [comment]
The glow does not occur
![Screenshot_53](https://github.com/Provismet/ProviHealth/assets/136928305/d314ca79-4de1-4da0-92b5-b47e2fd02e6e)

**Comment by OneWorldStudio** [comment]
It doesn't show anything on custom monsters

**Comment by Provismet** [comment]
I'll look further into this tomorrow. For now could you please confirm your settings.

- Set the health bars for all mobs to always be visible. Iron Golems are non-hostile, so their health bars will not be visible at full health on the default settings.
- Try clearing the blacklist.
- Try setting the in-world health bar scale to the maximum.
- Can you confirm if the damage particles still spawn?
  - If they cannot be seen, try setting them to falling mode so they have gravity. (Makes them spread out more.)

**Comment by OneWorldStudio** [comment]
I have tried all the settings, but the progress there is a plugin ItemsAdder catches these objects, although I would no
![Screenshot_54](https://github.com/Provismet/ProviHealth/assets/136928305/48ab55b5-2ca0-4d64-8fc3-1b88cb424445)
![Screenshot_39](https://github.com/Provismet/ProviHealth/assets/136928305/95cd1228-d694-43ea-9009-37497a30614f)
t really like it to be so.

**Comment by Provismet** [comment]
Sorry that this is going back and forth so much, but that's simply the nature of trying to get a client-side mod to interact in any way with a server-side plugin when neither knows of the other. It just requires a lot of troubleshooting.

I've push a new [experimental commit](https://github.com/Provismet/ProviHealth/actions/runs/7152662586). This build completely removes the visibility check from mobs. Please test it with your custom mobs (ensuring that in your settings the in-world health bars for all mobs are set to "Show").

If this works I can fine-tune it over time, but if this does not work then it would seem the compatibility is not possible.

**Comment by OneWorldStudio** [comment]
Eh, it doesn't work

**Comment by Provismet** [comment]
In that case it seems that it's simply not possible to make the mod compatible with modelengine mobs.  
Thank you for helping me investigate this, however.

**Comment by OneWorldStudio** [comment]
> В таком случае кажется, что сделать мод совместимым с мобами modelengine просто невозможно. Однако спасибо, что помогли мне расследовать это.

okay, thanks
